### ISSUE TITLE
Cannot start on Debian 10

### ISSUE THREAD

**Issue by hstock** [flathub/org.signal.Signal#136]
when starting on Debian 10 it gives the following error:

```
Unhandled Error: Error: /run/user/5003/app/org.signal.Signal/.org.chromium.Chromium.qhC9Nn: Fehler beim Mappen des Shared Objects
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
```

Problem seems to be that `/app/bin/signal` contains 

    export TMPDIR="$XDG_RUNTIME_DIR/app/$FLATPAK_ID"

However the location is mounted with `noexec`

    tmpfs on /run/user/5003/app/org.signal.Signal type tmpfs (rw,nosuid,nodev,noexec,relatime,size=2463784k,mode=755)

Not sure whether this is the wrong location or this is a problem with Flatpak.

**Comment by hstock** [comment]
```
flatpak --version
Flatpak 1.6.2
```

Might be that Debian sets `noexec` as the default for `tmpfs`.

**Comment by pabl0** [comment]
Does not seem to be the case always on Debian 10.

`$ flatpak run --command=mount org.signal.Signal | grep /run/user/$(id -u)/app/org.signal.Signal
tmpfs on /run/user/1000/app/org.signal.Signal type tmpfs (rw,nosuid,nodev,relatime,size=1624060k,mode=700,uid=1000,gid=1000)
$ dpkg -l flatpak
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version         Architecture Description
+++-==============-===============-============-=================================================
ii  flatpak        1.2.5-0+deb10u1 amd64        Application deployment framework for desktop apps
`
