### ISSUE TITLE
Render process is gone, Exit 132 on KDE 6.1.1, Fedora 40, Signal 7.15.0

### ISSUE THREAD

**Issue by elijahsgh** [flathub/org.signal.Signal#684]
I don't remember when I last used the Signal app but I used it a lot a month or so ago with no issues. Recently it seems to have stopped working.
I am using org.signal.Signal from flathub.

I have tried a few of the things mentioned on some of the other tickets from enabling the System Bus via flatpak/flatseal/discover, etc. I tried toggling the wayland flag on and off. I removed the signal data directory, etc.

This is what I get each time:
```
{"level":30,"time":"2024-07-04T05:36:52.069Z","msg":"Begin ensuring permissions"}
{"level":30,"time":"2024-07-04T05:36:52.069Z","msg":"Ensuring file permissions for 4 files"}
{"level":30,"time":"2024-07-04T05:36:52.070Z","msg":"Finish ensuring permissions in 1ms"}
{"level":30,"time":"2024-07-04T05:36:52.081Z","msg":"main window is ready-to-show"}
{"level":30,"time":"2024-07-04T05:36:52.081Z","msg":"showing main window"}
{"level":30,"time":"2024-07-04T05:36:52.081Z","msg":"System tray service: rendering no tray"}
{"level":40,"time":"2024-07-04T05:36:52.127Z","msg":"MainSQL: Database log code=284: automatic index on reactions(messageId)"}
{"level":30,"time":"2024-07-04T05:36:52.176Z","msg":"Prevent display sleep service: allowing display sleep"}
{"level":30,"time":"2024-07-04T05:36:52.177Z","msg":"Background throttling enabled because no call is active"}
Render process is gone: Error: Reason: crashed, Exit Code: 132
    at App.<anonymous> (/app/Signal/resources/app.asar/app/global_errors.js:88:7)
    at App.emit (node:events:518:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:83836)
    at WebContents.emit (node:events:518:28)
{"level":50,"time":"2024-07-04T05:36:52.952Z","msg":"Render process is gone: Error: Reason: crashed, Exit Code: 132\n    at App.<anonymous> ([REDACTED]/app/global_errors.js:88:7)\n    at App.emit (node:events:518:28)\n    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:83836)\n    at WebContents.emit (node:events:518:28)"}
{"level":30,"time":"2024-07-04T05:36:54.383Z","msg":"main window closed event"}
{"level":30,"time":"2024-07-04T05:36:54.383Z","msg":"System tray service: updating main window. Previously, there was a window, and now there is not"}
```

As a sanity check, I grabbed the Signal desktop app from the official repo, built it, and ran it without issue.

**Comment by elijahsgh** [comment]
This is solved.
I had disabled AVX for a game or something a long time ago.
Reenabled it when I noticed.
Signal works now.
