### ISSUE TITLE
onDatabaseError: Removing malformed key

### ISSUE THREAD

**Issue by akvadrako** [flathub/org.signal.Signal#694]
Every time I start Signal 7.16.0 I get this message:

> Database startup error:
> 
> Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
>     at getSQLKey ([REDACTED]/app/main.js:1244:39)
>     at initializeSQL ([REDACTED]/app/main.js:1277:11)
>     at App.<anonymous> ([REDACTED]/app/main.js:1485:20)

And in the logs it says:

> {"level":30,"time":"2024-07-25T17:20:51.656Z","msg":"getSQLKey: decrypting key"}
> {"level":50,"time":"2024-07-25T17:20:53.210Z","msg":"onDatabaseError: Removing malformed key"}
> {"level":30,"time":"2024-07-25T17:20:53.212Z","msg":"config/set: Saving user config to disk"}
> {"level":30,"time":"2024-07-25T17:20:53.218Z","msg":"config/set: Saved user config to disk"}
> {"level":30,"time":"2024-07-25T17:20:53.218Z","msg":"getSQLKey: migrating key"}
> {"level":30,"time":"2024-07-25T17:20:53.218Z","msg":"getSQLKey: updating encrypted key in the config"}
> {"level":30,"time":"2024-07-25T17:20:53.218Z","msg":"config/set: Saving user config to disk"}
> {"level":30,"time":"2024-07-25T17:20:53.220Z","msg":"config/set: Saved user config to disk"}
> {"level":30,"time":"2024-07-25T17:20:53.221Z","msg":"config/set: Saving user config to disk"}
> {"level":30,"time":"2024-07-25T17:20:53.222Z","msg":"config/set: Saved user config to disk"}

I have tried deleting my flatpak data directory `del ~/.var/app/org.signal.Signal/` but it doesn't help.

**Comment by akvadrako** [comment]
Perhaps this is related to using the new safeStorage API:

https://github.com/signalapp/Signal-Desktop/pull/6849#issuecomment-2218845070

Seems related: https://github.com/flathub/com.vscodium.codium/issues/239
