### ISSUE TITLE
Unable to access the database encryption key

### ISSUE THREAD

**Issue by marek22k** [flathub/org.signal.Signal#752]
Hello,

after I updated Signal, it no longer works.

Log:
```
$ flatpak run org.signal.Signal
Debug: Using password store: basic
Debug: Will run signal with the following arguments: --password-store=basic
Debug: Additionally, user gave: 
Set Windows Application User Model ID (AUMID) { AUMID: 'org.whispersystems.signal-desktop' }
NODE_ENV production
NODE_CONFIG_DIR /app/Signal/resources/app.asar/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME ciel
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
SIGNAL_ENABLE_HTTP undefined
userData: /home/marek/.var/app/org.signal.Signal/config/Signal
config/get: Successfully read user config file
config/get: Successfully read ephemeral config file
making app single instance
LaunchProcess: failed to execvp:
xdg-settings
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 18:19:48.261: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:19:48.261: Failed to load module "canberra-gtk-module"
{"level":30,"time":"2024-09-27T18:19:48.569Z","msg":"got fast localeOverride setting null"}
{"level":30,"time":"2024-09-27T18:19:48.570Z","msg":"app.ready: hour cycle preference: UnknownPreference"}
{"level":30,"time":"2024-09-27T18:19:48.570Z","msg":"app.ready: preferred system locales: en-US, en"}
{"level":30,"time":"2024-09-27T18:19:48.571Z","msg":"locale: Supported locales: af-ZA, ar, az-AZ, bg-BG, bn-BD, bs-BA, ca, cs, da, de, el, en, es, et-EE, eu, fa-IR, fi, fr, ga-IE, gl-ES, gu-IN, he, hi-IN, hr-HR, hu, id, it, ja, ka-GE, kk-KZ, km-KH, kn-IN, ko, ky-KG, lt-LT, lv-LV, mk-MK, ml-IN, mr-IN, ms, my, nb, nl, pa-IN, pl, pt-BR, pt-PT, ro-RO, ru, sk-SK, sl-SI, sq-AL, sr, sv, sw, ta-IN, te-IN, th, tl-PH, tr, ug, uk-UA, ur, vi, yue, zh-CN, zh-HK, zh-Hant"}
{"level":30,"time":"2024-09-27T18:19:48.571Z","msg":"locale: Preferred locales: en-US, en"}
{"level":30,"time":"2024-09-27T18:19:48.571Z","msg":"locale: Locale Override: null"}
{"level":30,"time":"2024-09-27T18:19:48.573Z","msg":"locale: Matched locale: en"}
{"level":40,"time":"2024-09-27T18:19:48.615Z","msg":"intl.onWarn [@formatjs/intl] \"defaultRichTextElements\" was specified but \"message\" was not pre-compiled. \nPlease consider using \"@formatjs/cli\" to pre-compile your messages for performance.\nFor more details see https://formatjs.io/docs/getting-started/message-distribution"}
{"level":30,"time":"2024-09-27T18:19:48.616Z","msg":"locale: Text info direction for en: ltr"}
{"level":50,"time":"2024-09-27T18:19:48.616Z","msg":"Detected change in safeStorage backend, can't decrypt DB key (previous: gnome_libsecret, current: basic_text)"}
{"level":30,"time":"2024-09-27T18:19:48.617Z","msg":"getSystemTraySetting got value DoNotUseSystemTray"}
{"level":30,"time":"2024-09-27T18:19:48.617Z","msg":"getSystemTraySetting returning DoNotUseSystemTray"}
{"level":30,"time":"2024-09-27T18:19:48.619Z","msg":"app ready"}
{"level":30,"time":"2024-09-27T18:19:48.619Z","msg":"starting version 7.24.1"}
{"level":30,"time":"2024-09-27T18:19:48.619Z","msg":"media access status [object Undefined] [object Undefined]"}
{"level":30,"time":"2024-09-27T18:19:48.624Z","msg":"got fast theme-setting value system"}
{"level":30,"time":"2024-09-27T18:19:48.642Z","msg":"got fast theme-setting value system"}
{"level":30,"time":"2024-09-27T18:19:48.643Z","msg":"got fast spellcheck setting true"}
{"level":30,"time":"2024-09-27T18:19:48.643Z","msg":"Initializing BrowserWindow config: {\"show\":false,\"width\":800,\"height\":744,\"minWidth\":300,\"minHeight\":200,\"autoHideMenuBar\":false,\"titleBarStyle\":\"default\",\"backgroundColor\":\"#121212\",\"webPreferences\":{\"devTools\":false,\"spellcheck\":true,\"enableBlinkFeatures\":\"CSSPseudoDir,CSSLogical\",\"enablePreferredSizeMode\":true,\"nodeIntegration\":false,\"nodeIntegrationInWorker\":false,\"sandbox\":false,\"contextIsolation\":true,\"preload\":\"[REDACTED]/preload.bundle.js\",\"backgroundThrottling\":true,\"disableBlinkFeatures\":\"Accelerated2dCanvas,AcceleratedSmallCanvases\"},\"icon\":\"[REDACTED]/images/signal-logo-desktop-linux.png\",\"x\":1035,\"y\":236}"}
{"level":30,"time":"2024-09-27T18:19:48.702Z","msg":"spellcheck: user locales: [\"en-US\",\"en\"]"}
{"level":30,"time":"2024-09-27T18:19:48.702Z","msg":"spellcheck: available spellchecker languages: [\"af\",\"bg\",\"ca\",\"cs\",\"cy\",\"da\",\"de\",\"de-DE\",\"el\",\"en\",\"en-AU\",\"en-CA\",\"en-GB\",\"en-GB-oxendict\",\"en-US\",\"es\",\"es-419\",\"es-AR\",\"es-ES\",\"es-MX\",\"es-US\",\"et\",\"fa\",\"fo\",\"fr\",\"fr-FR\",\"he\",\"hi\",\"hr\",\"hu\",\"hy\",\"id\",\"it\",\"it-IT\",\"ko\",\"lt\",\"lv\",\"nb\",\"nl\",\"pl\",\"pt\",\"pt-BR\",\"pt-PT\",\"ro\",\"ru\",\"sh\",\"sk\",\"sl\",\"sq\",\"sr\",\"sv\",\"ta\",\"tg\",\"tr\",\"uk\",\"vi\"]"}
{"level":30,"time":"2024-09-27T18:19:48.703Z","msg":"spellcheck: setting languages to: [\"en-US\",\"en\"]"}
2024-09-27 18:19:48.900: ERROR CORE sqlcipher_page_cipher: hmac check failed for pgno=1
2024-09-27 18:19:48.900: ERROR CORE sqlite3Codec: error decrypting page 1 data: 1
2024-09-27 18:19:48.900: ERROR CORE sqlcipher_codec_ctx_set_error 1
{"level":40,"time":"2024-09-27T18:19:48.901Z","msg":"MainSQL: Database log code=26: file is not a database in \"PRAGMA journal_mode = WAL\""}
{"level":30,"time":"2024-09-27T18:19:48.901Z","msg":"MainSQL: migrateDatabase: Migration without cipher change failed"}
2024-09-27 18:19:48.935: ERROR CORE sqlcipher_page_cipher: hmac check failed for pgno=1
2024-09-27 18:19:48.935: ERROR CORE sqlite3Codec: error decrypting page 1 data: 1
2024-09-27 18:19:48.935: ERROR CORE sqlcipher_codec_ctx_set_error 1
{"level":40,"time":"2024-09-27T18:19:48.936Z","msg":"MainSQL: Database log code=26: statement aborts at 2: [PRAGMA user_version] file is not a database"}
{"level":50,"time":"2024-09-27T18:19:48.937Z","msg":"MainSQL: Database startup error: SqliteError: file is not a database\n    at Database.pragma ([REDACTED]/node_modules/@signalapp/better-sqlite3/lib/methods/pragma.js:11:31)\n    at getUserVersion ([REDACTED]/ts/sql/util.js:132:13)\n    at migrateSchemaVersion ([REDACTED]/ts/sql/Server.js:404:54)\n    at openAndMigrateDatabase ([REDACTED]/ts/sql/Server.js:436:5)\n    at openAndSetUpSQLCipher ([REDACTED]/ts/sql/Server.js:458:14)\n    at initialize ([REDACTED]/ts/sql/Server.js:496:10)\n    at MessagePort.<anonymous> ([REDACTED]/ts/sql/mainWorker.js:69:41)\n    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)\n    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)"}
{"level":50,"time":"2024-09-27T18:19:48.937Z","msg":"Failed to get zoom factor {\"name\":\"SqliteError\"}"}
{"level":30,"time":"2024-09-27T18:19:49.240Z","msg":"got fast theme-setting value system"}
{"level":50,"time":"2024-09-27T18:19:49.718Z","msg":"sql.initialize was unsuccessful; returning early"}
{"level":30,"time":"2024-09-27T18:19:49.719Z","msg":"close event {\"readyForShutdown\":false,\"shouldQuit\":false}"}
{"level":30,"time":"2024-09-27T18:19:49.720Z","msg":"maybeRequestCloseConfirmation: Checking to see if close confirmation is needed"}
{"level":50,"time":"2024-09-27T18:20:44.274Z","msg":"onDatabaseError: Quitting application"}
{"level":30,"time":"2024-09-27T18:20:44.275Z","msg":"main window closed event"}
{"level":30,"time":"2024-09-27T18:20:44.275Z","msg":"quit event {\"hasEventBeenPrevented\":false,\"windowCount\":0,\"mainWindowExists\":false}"}
{"level":50,"time":"2024-09-27T18:20:44.276Z","msg":"Error occurred in handler for 'sql-channel:read': {\"name\":\"SqliteError\"}"}
{"level":50,"time":"2024-09-27T18:20:44.277Z","msg":"maybeRequestCloseConfirmation: Response never received; continuing with close."}
{"level":50,"time":"2024-09-27T18:20:44.277Z","msg":"MainSQL close, failed: SqliteError: file is not a database\n    at Database.pragma ([REDACTED]/node_modules/@signalapp/better-sqlite3/lib/methods/pragma.js:11:31)\n    at getUserVersion ([REDACTED]/ts/sql/util.js:132:13)\n    at migrateSchemaVersion ([REDACTED]/ts/sql/Server.js:404:54)\n    at openAndMigrateDatabase ([REDACTED]/ts/sql/Server.js:436:5)\n    at openAndSetUpSQLCipher ([REDACTED]/ts/sql/Server.js:458:14)\n    at initialize ([REDACTED]/ts/sql/Server.js:496:10)\n    at MessagePort.<anonymous> ([REDACTED]/ts/sql/mainWorker.js:69:41)\n    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)\n    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)"}
```

![signal](https://github.com/user-attachments/assets/60a57a28-845f-42e7-b826-ebb4f6cb18c2)

Workaround:
Settings `SIGNAL_PASSWORD_STORE=gnome-libsecret` in Flatseal.

**Comment by bermeitinger-b** [comment]
> Workaround:
> Settings SIGNAL_PASSWORD_STORE=gnome-libsecret in 
Flatseal

That's not a workaround, it's the intended and only way.

**Comment by marek22k** [comment]
Mhh, okay. Is that documented somewhere? I didn't get a notification after the update? Or should I just read the changelog?

**Comment by TheRoarkster** [comment]
Same error.  The proposed solution in the error message doesn't work.  The solution above mentions `Flatseal`, which I don't have installed.  Is there a way to fix this without `Flatseal` installed?

**Comment by bshephar** [comment]
> Same error. The proposed solution in the error message (`flatpak run org.signal.Signal --password-store="gnome-libsecret" `) doesn't work. The solution above mentions `Flatseal`, which I don't have installed. Is there a way to fix this without `Flatseal` installed?

https://github.com/flathub/org.signal.Signal/issues/753#issuecomment-2380653595
