### ISSUE TITLE
Signal encryption keyring changed from gnome_libsecret to basic_text

### ISSUE THREAD

**Issue by RelicCornhusk** [flathub/org.signal.Signal#753]
For some reason, despite not having made any major updates on my OS (Fedora Workstation 40), I now get this message when trying to open Signal:

Database startup error:

```
SafeStorageBackendChangeError: Detected change in safeStorage backend, can't decrypt DB key (previous: gnome_libsecret, current: basic_text)
    at getSQLKey ([REDACTED]/app/main.js:1256:11)
    at initializeSQL ([REDACTED]/app/main.js:1317:11)
    at App.<anonymous> ([REDACTED]/app/main.js:1538:20)

App Version: 7.24.1
OS: linux
```
Any idea why this is happening? I've tried opening signal through the terminal with --password-store=gnome-libsecret and --password-store=basic-text. Passing gnome-libsecret as the argument for the command seems to make it work, but it says that there is a problem with my database and that it must be deleted. Here is the exact error:

```
Database startup error:

SafeStorageBackendChangeError: Detected change in safeStorage backend, can't decrypt DB key (previous: gnome_libsecret, current: basic_text)
    at getSQLKey ([REDACTED]/app/main.js:1256:11)
    at initializeSQL ([REDACTED]/app/main.js:1317:11)
    at App.<anonymous> ([REDACTED]/app/main.js:1538:20)

App Version: 7.24.1
OS: linux
```

**Comment by Maners** [comment]
Same just started happening for me, also on Fedora 40

**Comment by liamreoch** [comment]
Can confirm, I updated and got this error.

![Screenshot from 2024-09-28 15-09-59](https://github.com/user-attachments/assets/75825631-dba2-42d4-a933-29d41b7506d8)

Running from terminal with that flag then leads this this:

![Screenshot from 2024-09-28 15-12-36-1](https://github.com/user-attachments/assets/1fe8b8de-51ac-4c96-95cd-6cf2caef963d)

**Comment by bermeitinger-b** [comment]
Use the env var **SIGNAL_PASSWORD_STORE** and set it to **gnome-libsecret**

**Comment by bellegarde-c** [comment]
@bermeitinger-b Not working here, every startup Signal tells me DB is broken.

**Comment by RelicCornhusk** [comment]
> Use flatseal to set the env var **SIGNAL_PASSWORD_STORE** to **gnome-libsecret**

I can do that and delete my database, but I'm trying to find a way of not needing to delete my database.

**Comment by DeltaLima** [comment]
Having the same issue. Debian stable bookworm here with flatpak 1.14.10 from debian repo.
I started the Signal flatpak as told with the argument `--password-store="gnome-libsecret"` and it worked fine for me. But to keep it working, I have to run Signal everytime with this argument. 

```
flatpak run org.signal.Signal --password-store="gnome-libsecret"
```
there was no need to delete anything, just worked again.


A short grep in signals flatpak directory `~/.var/app/org.signal.Signal/` revealed that "gnome_libsecret" is already set in the config file, but seem to be ignored

```
$ grep -r "gnome_libsecret" *
config/Signal/config.json:  "safeStorageBackend": "gnome_libsecret"
```

**Comment by salim-b** [comment]
> But to keep it working, I have to run Signal everytime with this argument.

To set it permanently for your user set `SIGNAL_PASSWORD_STORE` via [Flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal) or `flatpak override` on the terminal:

```sh
flatpak override org.signal.Signal --user --env=SIGNAL_PASSWORD_STORE=gnome-libsecret
```

**Comment by minosimo** [comment]
I have tried to assemble troubleshooting instructions in one place here: https://community.signalusers.org/t/warning-do-not-update-from-flathub-database-error/63222#p-251892-database-error-keyring-backend-has-changed-5

If anyone needs help, please ask in that thread rather than on github.

**Comment by minosimo** [comment]
I have that entry in my keystore as well. I'm not sure where it came from.

I can only get Signal to launch with gnome-libsecret when the keyring entry is in a Chromium Safe Storage entry with the application set to Signal. I am generating the entry with a script in Electron Fiddle:

```
const { app, safeStorage } = require('electron');
const { join } = require('node:path');
const { readFileSync, writeFileSync } = require('node:fs');

const folder = '/home/simon/.var/app/org.signal.Signal/config/Signal';
app.setPath('userData', folder);
app.setName('Signal');

app.on('ready', () => {
  const configPath = join(folder, 'config.json');

  const json = readFileSync(configPath, 'utf8');
  // Save backup
  writeFileSync(join(folder, 'config.json.bak'), json);

  const config = JSON.parse(json);
  if (!config.key) {
    console.error('Decrypted key not found in config.json');
    app.quit(1);
    return;
  }

  
  const key = config.key;
  const encrypted = safeStorage.encryptString(key).toString('hex');

  console.log(encrypted)

  const newConfig = {
    ...config,
    encryptedKey: encrypted,
    key: undefined,
  };
  const newJson = JSON.stringify(newConfig, null, 2);
  writeFileSync(configPath, newJson);

  console.log('Success');
  app.quit();
})
```

**Comment by mamama1** [comment]
had to set SIGNAL_PASSWORD_STORE=basic and restore a config.json backup with the unencrypted key. if i leave SIGNAL_PASSWORD_STORE=gmome-libsecret, it encrypts the key at start in the config.json but doesn't put it into the system keyring.
Fedora 40 Gnome.

**Comment by emdnaia** [comment]
> > But to keep it working, I have to run Signal everytime with this argument.
> 
> To set it permanently for your user, set `SIGNAL_PASSWORD_STORE` via [Flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal) or `flatpak override` on the terminal:
> 
> ```shell
> flatpak override org.signal.Signal --user --env=SIGNAL_PASSWORD_STORE=gnome-libsecret
> ```

fastest solution

**Comment by minosimo** [comment]
> > I have tried to assemble troubleshooting instructions in one place here: https://community.signalusers.org/t/warning-do-not-update-from-flathub-database-error/63222#p-251892-database-error-keyring-backend-has-changed-5
> > If anyone needs help, please ask in that thread rather than on github.
> 
> The tutoral instructs to use:
> 
> `secret-tool search application Signal`
> 
> which did not return anything to me. However, browsing with Seahorse I have found an entry that had no label at all but had `app_id` attribute set to `org.signal.Signal`. Running:
> 
> `secret-tool search app_id org.signal.Signal`
> 
> revealed that the entry was created on Sept 26th 2024 so it's not some old leftover. How can I make signal use this one and try to recover using it? My `config.json` has encrypted password stored and I don't have backup of it, so this option won't work.

On a Debian install from the .deb, the key written is called "Chromium Safe Storage" and the attribute is application: Signal, so that's probably the correct key.

**Comment by bbhtt** [comment]
> config.json backup with the unencrypted key. if i leave SIGNAL_PASSWORD_STORE=gmome-libsecret, it encrypts the key at start in the config.json but doesn't put it into the system keyring.

Try testing `basic` -> `gnome_libsecret` migration with this PR https://github.com/flathub/org.signal.Signal/pull/756 It should work.

**Comment by RelicCornhusk** [comment]
> > config.json backup with the unencrypted key. if i leave SIGNAL_PASSWORD_STORE=gmome-libsecret, it encrypts the key at start in the config.json but doesn't put it into the system keyring.
> 
> Try testing `basic` -> `gnome_libsecret` migration with this PR #756 It should work.
> 
> If you previously had `basic` storage, run it as `flatpak run --env=SIGNAL_PASSWORD_STORE=gnome-libsecret org.signal.Signal` and check if it's storing in the keyring correctly.

I just tested the PR build and it still won't allow me to get back to my old database despite switching to gnome-libsecret, it prompts me to delete it and restart the application. Is that expected? Should I just do that or is there a chance that there will be a fix that will allow me to go back to my messages/media?

**Comment by distbit0** [comment]
I managed to resolve this due to finding an unintentional backup of my config file located at ~/.config/Signal/config.json from when I used to use a non-flatpak version of Signal, whereas my current config file (which only conatined the encrypted key) is located at ~/.var/app/org.signal.Signal/config/Signal/config.json.

This may be helpful to anyone who previously used a non-flatpak signal package before switching to flatkpak, or vice versa, due to different package formats using different config file paths.

**Comment by SoLoR1** [comment]
> had to set SIGNAL_PASSWORD_STORE=basic and restore a config.json backup with the unencrypted key. if i leave SIGNAL_PASSWORD_STORE=gmome-libsecret, it encrypts the key at start in the config.json but doesn't put it into the system keyring. Fedora 40 Gnome.
> 
> what a royal mess for people without a backup of a supposed to be stateless application

I had same issue on Linux Mint 22, luckily i could restore config.json from daily timeshift backup and switch back to basic password store.

**Comment by hotrooibos** [comment]
Fedora 40. Got this error this morning. Tried the above solutions (flatseal, flatpak override...), but nothing works. I get the following "A database error occurred".
![Screenshot from 2024-09-30 16-58-21](https://github.com/user-attachments/assets/ea71fb5f-c594-416d-815d-3f1d242e2a6a).

**Comment by hotrooibos** [comment]
> @hotrooibos you probably are facing this issue #723. 

I only get this once I change the SIGNAL_PASSWORD_STORE variable (either with the above command line, or through flatseal) to gnome-libsecret. If I revert it to basic, I'm back with the current issue. Since I've never installed a non-flatpak version of Signal, I guess my local data is now lost.

**Comment by timeabolition** [comment]
> Use flatseal to set the env var **SIGNAL_PASSWORD_STORE** to **gnome-libsecret**

This seemed to solve the problem for me, although I get an alert next to the value suggesting something is wrong.

**Comment by bermeitinger-b** [comment]
This yellow exclamation mark tells you that this value was changed from the default.

**Comment by timeabolition** [comment]
> This yellow exclamation mark tells you that this value was changed from the default.

Thank you for the solution and the lesson!

**Comment by swalter972** [comment]
Nothing worked for me, don't have time to dig for this problem for now, any short answer (flatseal didnt work on latest mint) with resteing also ? Thanks

**Comment by bermeitinger-b** [comment]
Remove your config, and start with a new database.

**Comment by swalter972** [comment]
I don't want to remove my bueatiful Mint configuration, nore my grpahic card ^^
HOw do I delete the database and restart from scratch ? (nope uninstall and reinstall didnt do the job, nor the flatseal solution,)

**Comment by salim-b** [comment]
> HOw do I delete the database and restart from scratch ? (nope uninstall and reinstall didnt do the job, nor the flatseal solution,)

Either via `flatpak uninstall --delete-data org.signal.Signal` or via `rm -r ~/.var/app/org.signal.Signal` (supposed you're using the default user-config path). This applies to any Flatpak app.

**Comment by TheRoarkster** [comment]
Same issue on Manjaro.  Can someone who knows please confirm this is a bug and not a a feature?  Is it something that will be addressed in an update -- or is the "solution" for users to manually enter `flatpak override org.signal.Signal --user --env=SIGNAL_PASSWORD_STORE=gnome-libsecret` in a terminal?

**Comment by salim-b** [comment]
> Can someone who knows please confirm this is a bug and not a a feature

It is a precausion to avoid further users run into #723, but at the same time caused users that had already updated to the version released directly before that to have to resort to customizing the env var you mention.

>  Is it something that will be addressed in an update

I think OS keystore support can be enabled by default again once https://github.com/flathub/org.signal.Signal/pull/756 is merged.

**Comment by olaf-meyer** [comment]
I have a similar situation. Removing and installing Signal via flatpak is not helping also changing the password store didn't help.  If I run `flatpak run -v org.signal.Signal `, I get an error message:
`{"level":30,"time":"2024-10-02T09:24:04.464Z","msg":"spellcheck: user locales: [\"de-DE\",\"de\"]"}
{"level":30,"time":"2024-10-02T09:24:04.464Z","msg":"spellcheck: available spellchecker languages: [\"af\",\"bg\",\"ca\",\"cs\",\"cy\",\"da\",\"de\",\"de-DE\",\"el\",\"en\",\"en-AU\",\"en-CA\",\"en-GB\",\"en-GB-oxendict\",\"en-US\",\"es\",\"es-419\",\"es-AR\",\"es-ES\",\"es-MX\",\"es-US\",\"et\",\"fa\",\"fo\",\"fr\",\"fr-FR\",\"he\",\"hi\",\"hr\",\"hu\",\"hy\",\"id\",\"it\",\"it-IT\",\"ko\",\"lt\",\"lv\",\"nb\",\"nl\",\"pl\",\"pt\",\"pt-BR\",\"pt-PT\",\"ro\",\"ru\",\"sh\",\"sk\",\"sl\",\"sq\",\"sr\",\"sv\",\"ta\",\"tg\",\"tr\",\"uk\",\"vi\"]"}
{"level":30,"time":"2024-10-02T09:24:04.464Z","msg":"spellcheck: setting languages to: [\"de-DE\",\"de\"]"}
2024-10-02 11:24:04.658: ERROR CORE sqlcipher_page_cipher: hmac check failed for pgno=1
2024-10-02 11:24:04.658: ERROR CORE sqlite3Codec: error decrypting page 1 data: 1
2024-10-02 11:24:04.658: ERROR CORE sqlcipher_codec_ctx_set_error 1
{"level":40,"time":"2024-10-02T09:24:04.659Z","msg":"MainSQL: Database log code=26: file is not a database in \"PRAGMA journal_mode = WAL\""}
{"level":30,"time":"2024-10-02T09:24:04.659Z","msg":"MainSQL: migrateDatabase: Migration without cipher change failed"}
2024-10-02 11:24:04.689: ERROR CORE sqlcipher_page_cipher: hmac check failed for pgno=1
2024-10-02 11:24:04.689: ERROR CORE sqlite3Codec: error decrypting page 1 data: 1
2024-10-02 11:24:04.689: ERROR CORE sqlcipher_codec_ctx_set_error 1
{"level":40,"time":"2024-10-02T09:24:04.690Z","msg":"MainSQL: Database log code=26: statement aborts at 2: [PRAGMA user_version] file is not a database"}
{"level":50,"time":"2024-10-02T09:24:04.690Z","msg":"MainSQL: Database startup error: SqliteError: file is not a database\n    at Database.pragma ([REDACTED]/node_modules/@signalapp/better-sqlite3/lib/methods/pragma.js:11:31)\n    at getUserVersion ([REDACTED]/ts/sql/util.js:132:13)\n    at migrateSchemaVersion ([REDACTED]/ts/sql/Server.js:404:54)\n    at openAndMigrateDatabase ([REDACTED]/ts/sql/Server.js:436:5)\n    at openAndSetUpSQLCipher ([REDACTED]/ts/sql/Server.js:458:14)\n    at initialize ([REDACTED]/ts/sql/Server.js:496:10)\n    at MessagePort.<anonymous> ([REDACTED]/ts/sql/mainWorker.js:69:41)\n    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)\n    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)"}
{"level":50,"time":"2024-10-02T09:24:04.691Z","msg":"Failed to get zoom factor {\"name\":\"SqliteError\"}"}
` 
Is error file is not a database caused by the secret store or is this an other issue?

**Comment by mtimofiiv** [comment]
Same here. I've re-created the database now 4 times. I have tried everything in this thread already. I have the env var `SIGNAL_PASSWORD_STORE=gnome-libsecret` and the config file has the key and `"safeStorageBackend": "gnome_libsecret"` is set.

My output in terminal matches @olaf-meyer's. I'm on Pop_OS.

**Comment by adonig** [comment]
Is there no official fix yet?

**Comment by MoeJoe551** [comment]
Hey people, apparently I've got the same problem, I've read through here and tried to solve it (I'm no tech geek at all) and nothing worked..
First I had the message where I could only click copy error and quit (the one telling me the keyring changed from gnome_libsecret to basic_text) and I tried to use the terminal with:

flatpak run org.signal.Signal --password-store="gnome-libsecret"

and it was saying something that I didn't understand and in the end something was failed it said. Then I tried:

flatpak override org.signal.Signal --user --env=SIGNAL_PASSWORD_STORE=gnome-libsecret

and again nothing really changed, I just got the other error message where I can also choose to delete data and restart. But I'd really much prefer to keep my data.. I also tried to find the key in seahorse (which I hadn't downloaded before so I didn't find any key..)
Any ideas about this? I really have no clue about all this tech stuff :/
Thanks!

**Comment by illwieckz** [comment]
> > I have tried to assemble troubleshooting instructions in one place here: https://community.signalusers.org/t/warning-do-not-update-from-flathub-database-error/63222#p-251892-database-error-keyring-backend-has-changed-5
> > If anyone needs help, please ask in that thread rather than on github.
> 
> The tutoral instructs to use:
> 
> `secret-tool search application Signal`
> 
> which did not return anything to me. However, browsing with Seahorse I have found an entry that had no label at all but had `app_id` attribute set to `org.signal.Signal`. Running:
> 
> `secret-tool search app_id org.signal.Signal`
> 
> revealed that the entry was created on Sept 26th 2024 so it's not some old leftover. How can I make signal use this one and try to recover using it? My `config.json` has encrypted password stored and I don't have backup of it, so this option won't work.

I'm in the exact same situation as this one. On my end this app_id entry is from 2024-09-27, so very recent, around the days Signal started to work for me.

No suggested solution makes me possible to run Signal (changing the password store to basic asks me to deleted my data).

**Comment by mtimofiiv** [comment]
> > Same here. I've re-created the database now 4 times. I have tried everything in this thread already. I have the env var `SIGNAL_PASSWORD_STORE=gnome-libsecret` and the config file has the key and `"safeStorageBackend": "gnome_libsecret"` is set.
> > My output in terminal matches @olaf-meyer's. I'm on Pop_OS.
> > I don't care about losing my messages, so happy to test.
> 
> Set the password store to basic. https://community.signalusers.org/t/troubleshooting-guide-database-error-after-flatpak-update-from-flathub/63222

This worked to fix the immediate issue, the app now works as it did before. Thanks!

**Comment by adonig** [comment]
My dad had this issue on his laptop a week ago. I sent him the troubleshooting instructions above. I'm not sure whether he tried it yet. Today after doing updates I got the same error on Fedora 40:

![Screenshot from 2024-10-10 12-28-38](https://github.com/user-attachments/assets/2301bf0d-7950-4cf8-b2cb-79d8cde89eea)

I followed the given instructions but the command `secret-tool search application Signal` returns nothing.

I made a backup of the `~/.var/app/org.signal.Signal`, deleted that folder and started Signal with the basic password store.

I had to link the laptop again now all conversations are gone. Yay ... 2024, the year of the Linux desktop! 👏👏👏

If anyone finds a solution to bring back my data using the backup or some other hack, let me know.

**Comment by mamama1** [comment]
I'm blaming Signal for this.
Do you actually HAVE a backup?

**Comment by minosimo** [comment]
> My dad had this issue on his laptop a week ago. I sent him the troubleshooting instructions above. I'm not sure whether he tried it yet. Today after doing updates I got the same error on Fedora 40:
> 
> ![Screenshot from 2024-10-10 12-28-38](https://private-user-images.githubusercontent.com/900404/375336851-2301bf0d-7950-4cf8-b2cb-79d8cde89eea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NTczNTcsIm5iZiI6MTcyODU1NzA1NywicGF0aCI6Ii85MDA0MDQvMzc1MzM2ODUxLTIzMDFiZjBkLTc5NTAtNGNmOC1iMmNiLTc5ZDhjZGU4OWVlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQxMDQ0MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NGMxMGUwMWIwY2FiN2U0NTIzOTI5YjE3OTNhZDZmZTUyM2ZiMTk4MWJhZTY5MjQ1ODZjMzUwMjEyODg1MTU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FV9Z6NZoX-p1obCTKb2rMdh6FZZpqJfFjI4QNbPKs5Y)
> 
> I followed the given instructions but the command `secret-tool search application Signal` returns nothing.
> 
> I made a backup of the `~/.var/app/org.signal.Signal`, deleted that folder and started Signal with the basic password store.
> 
> I had to link the laptop again now all conversations are gone. Yay ... 2024, the year of the Linux desktop! 👏👏👏
> 
> If anyone finds a solution to bring back my data using the backup or some other hack, let me know.

Before resetting Signal, did you try starting with the password store set to gnome-libsecret?

**Comment by adonig** [comment]
> Before resetting Signal, did you try starting with the password store set to gnome-libsecret?

I did `flatpak run org.signal.Signal --password-store"gnome-libsecret"` but it looks like flatpak run doesn't pass the command line args following the app.

I restored the backup now and tried this:

`flatpak override --user --env=SIGNAL_PASSWORD_STORE=gnome-libsecret org.signal.Signal && flatpak run org.signal.Signal`

Now I get the error message telling me to contact Signal support:

![Screenshot from 2024-10-10 12-56-53](https://github.com/user-attachments/assets/5ba93193-02fb-40fc-92e3-7b1ba35b7679)

That's probably because there is no key in the keystore, like I confirmed before using `secret-tool`.

So I probably have to delete the Signal folder and all my messages again to get a working Signal desktop client?

**Comment by minosimo** [comment]
The update that causes the database to become unreadable hasn't been live for some time. I assume you launched Signal maybe once in the past week, or kept it running for a long time?

Otherwise, yes, if the Signal entry is not in the keyring, and you don't have a config.json with the unencrypted key in it, you will need to start fresh without the conversation history.

**Comment by adonig** [comment]
> The update that causes the database to become unreadable hasn't been live for some time. I assume you launched Signal maybe once in the past week, or kept it running for a long time?

I kept it running for like three weeks. Today I updated the kernel and did a reboot and the issue showed up. My dad got the issue last week. I hope he has a Signal entry in his keyring because if I'm going to delete his Signal messages, he's probably never going to do an update on his laptop again.

**Comment by salim-b** [comment]
> I'm blaming Signal for this.

You can blame Signal for building their desktop app on [Electron](https://en.wikipedia.org/wiki/Electron_(software_framework)).

You can blame Electron for relying on [Chromium](https://en.wikipedia.org/wiki/Chromium_(web_browser)) to render an app's front-end.

And finally, you can **blame Chromium for [implementing the "wrong" libsecret API](https://issues.chromium.org/issues/370535829)** – and causing this whole mess. 😉

**Comment by mamama1** [comment]
for me, i had to set SIGNAL_PASSWORD_STORE to basic and restore my config.json from a point in time where the key was unencrypted. then everything resumed to normal.

**Comment by mamama1** [comment]
> > I'm blaming Signal for this.
> 
> You can blame Signal for building their desktop app on [Electron](https://en.wikipedia.org/wiki/Electron_(software_framework)).
> 
> You can blame Electron for relying on [Chromium](https://en.wikipedia.org/wiki/Chromium_(web_browser)) to render an app's front-end.
> 
> And finally, you can **blame Chromium for [implementing the "wrong" libsecret API](https://issues.chromium.org/issues/370535829)** – and causing this whole mess. 😉

despite the fact that this is free software and we have very little ground to complain or blame at all, i think it would have been in Signal's responsibility to test properly and frequently and work around/handle errors like that. if their framework breaks, it is still them building on it and since no end user has the choise of changing the framework, imho it would've been Signals responsibility to take action accordingly.

imagine if something similar would have happened on windows, let alone android or iOS - Signal would be royally f**** by the sh*tstorm. they're just lucky, that the Linux desktop user base isn't that big.

**Comment by minosimo** [comment]
> I kept it running for like three weeks. Today I updated the kernel and did a reboot and the issue showed up. My dad got the issue last week. I hope he has a Signal entry in his keyring because if I'm going to delete his Signal messages, he's probably never going to do an update on his laptop again.

Ask him to run
`cat ~/.var/app/org.signal.Signal/config/Signal/config.json`
`secret-tool search application Signal`
`secret-tool search app_id org.signal.Signal`

That should give you all the info you need to know if he has the bad update or not. If his key is already encrypted but Signal is still running, the key must be floating around somewhere in RAM, but I couldn't tell you how to get at it.

**Comment by minosimo** [comment]
The issue was not with Signal, who tested the update and as far as I know have not caused anything to break. The database issues are only present in the flatpak build (which is managed by volunteers) that got pushed to flathub. Maybe the snap build as well.

salim-b tactfully left out a step. Before the broken update was published, this issue was noticed and reported in the pull request, but ignored. The broken update was merged to master immediately which automatically pushes the update to flathub. Even as people reported broken installs, the commit was not reverted for four days.

This is fundamentally an issue with flathub, where changes can be merged very easily by whoever manages a package. Distro repositories usually have a slightly more involved process. For instance Fedora uses a [karma](https://fedoraproject.org/wiki/Bodhi#Karma) system to determine whether updates can be published to stable or not.

**Comment by salim-b** [comment]
> salim-b tactfully left out a step.

Fair. Merging https://github.com/flathub/org.signal.Signal/pull/729 without more testing was a failure in hindsight. I guess the people involved felt some kind of urgency to act due to the accompanying [media reports / social media drama](https://stackdiary.com/signal-under-fire-for-storing-encryption-keys-in-plaintext/).

> This is fundamentally an issue with flathub, where changes can be merged very easily by whoever manages a package. Distro repositories usually have a slightly more involved process. For instance Fedora uses a [karma](https://fedoraproject.org/wiki/Bodhi#Karma) system to determine whether updates can be published to stable or not.

Yeah, OTOH official distro packages are almost always horribly out-of-date and Flatpak and Flathub provide the right technology/infrastructure to overcome the Linux desktop app packaging fragmentation.

IMHO, the real solution to the problem here would be Signal foundation taking over maintainership of this Flatpak.

**Comment by wrobbins** [comment]
I've been monitoring this issue since it happened to me. Regardless of the technicalities I mostly agree with the opinions recently expressed. Potentially losing all messages on a device is not good. 

> Yay ... 2024, the year of the Linux desktop! 

This is the kind of cynical sarcasm I enjoy and would have posted a similar message if I was feeling spicy. This is a bad look for Signal/Linux.

> imagine if something similar would have happened on windows, let alone android or iOS - Signal would be royally f**** 

Yep would have probably lost users

> IMHO, the real solution to the problem here would be Signal Foundation taking over maintainership of this Flatpak.
Yes OR
* Introduce automated testing to prevent issues like this happening again
* Eject from the Flatpak ecosystem and introduce a real Fedora repository with official builds. RPM fusion does not count.

Yes, it's cool that Signal is free. Signal is also free on iOS, MacOS, Windows, and Android. There are also a number of free alternatives that people might go to. It's already hard enough to convince people to switch to Signal. 

I recognize maintainers are probably frustrated that it happened and that people are piling on. If there's a postmortem I hope emotions can be left at the door and feedback like this will be considered. 

I'm a software developer, what can I do to help? Is it possible for people to donate to directly fund prevention of this in the future like adding tests etc ?

**Comment by salim-b** [comment]
> Introduce automated testing to prevent issues like this happening again
> I'm a software developer, what can I do to help?

PRs to this Flatpak are welcome AFAICT, so feel free to help out with this! I suppose it is quite a challenge to implement pairing of Signal Desktop with a main Signal app instance (Android/iOS; using some test account) in CI. And way too much to ask of volunteers IMHO.

> Eject from the Flatpak ecosystem and introduce a real Fedora repository with official builds. RPM fusion does not count.

That's the exact opposite of a solution to the packaging burden problem (and obviously would only work for Fedora users). See e.g. https://github.com/signalapp/Signal-Desktop/issues/1630, you're not the first person requesting packaging for their favorite distro.

**Comment by bermeitinger-b** [comment]
Please keep this thread about the key storage and probable recovery issues. Or ideas on how to migrate moving forwards.

**Comment by adonig** [comment]
I found a config.json with an encrypted key in my backup. Does this mean I can restore my messages somehow?

```json
{
  "mediaPermissions": true,
  "mediaCameraPermissions": true,
  "encryptedKey": "<REDACTED>",
  "safeStorageBackend": "gnome_libsecret"
}
```

**Comment by mamama1** [comment]
> I found a config.json with an encrypted key in my backup. Does this mean I can restore my messages somehow?
> 
> ```json
> {
>   "mediaPermissions": true,
>   "mediaCameraPermissions": true,
>   "encryptedKey": "<REDACTED>",
>   "safeStorageBackend": "gnome_libsecret"
> }
> ```

no, you need the unencrypted key version of the file, as i've stated earlier.

**Comment by heyakyra** [comment]
@Maners [wrote](https://github.com/flathub/org.signal.Signal/issues/753#issuecomment-2380856662):
> The tutoral instructs to use:
> 
> `secret-tool search application Signal`
> 
> which did not return anything to me. However, browsing with Seahorse I have found an entry that had no label at all but had `app_id` attribute set to `org.signal.Signal`.

@minosimo [wrote](https://github.com/flathub/org.signal.Signal/issues/753#issuecomment-2380862155):
> I have that entry in my keystore as well. I'm not sure where it came from.
> 
> I can only get Signal to launch with gnome-libsecret when the keyring entry is in a Chromium Safe Storage entry with the application set to Signal. I am generating the entry with a script in Electron Fiddle

Is there no way to just look at the existing entry without creating a new one? Or just decrypt it to switch back to the normal encryption?

**Comment by gichiba** [comment]
I deleted my database, uninstalled signal, used the flatpak --uninstall --delete-data command, and then re-installed with Pop!_OS shop, and it STILL gives me the database error, for `7.29.0` -- please, it's been 3 weeks now, I just want to keep chat history on my desktop so that I can converse with a keyboard. 

Is there any way to fix this without doing under-the-hood fiddling?

**Comment by solt87** [comment]
> I had to link the laptop again now all conversations are gone. Yay ... 2024, the year of the Linux desktop! 👏👏👏

It has nothing to do with "the (year of the) Linux desktop" (which has been here for 10+ years), and everything to do with "3rd party ~~program repositories~~ appstores". This is what happens when the "bad, baaad" distribution-provided packages and settings are replaced with 3rd-party cr@p. You get misbehaving programs, data loss, tons of "documentation" to read through, conflicting pieces of advice on solving the problem, and pointing the finger at someone else. Yay, alternative program sources! 👏👏👏

**Comment by bermeitinger-b** [comment]
Please stay on topic and leave angry and troll messages to yourself. This is not the right place.

**Comment by heyakyra** [comment]
@bermeitinger-b [wrote](https://github.com/flathub/org.signal.Signal/issues/753#issuecomment-2418939298):

> I would not dare introduce logic that checks all keyring entries—imagine the headline: Signal reads all your passwords.

Signal was responsible for creating that entry, right? Why not some logic that only searches for that entry in particular? 

Anyways, it's probably not worth the effort but it'd be worthwhile for those stuck in this weird state to have a manual script like @minosimo [created above](https://github.com/flathub/org.signal.Signal/issues/753#issuecomment-2380862155) (but to the effect of switching back to basic rather than creating a new keyring entry with the right label)

**Comment by heyakyra** [comment]
I tried to pipe the existing entry password to a new one with the right `application` attribute, but I get this error:

```bash
$  secret-tool lookup app_id org.signal.Signal | secret-tool store --label='Chromium Safe Storage' application Signal
secret-tool: password not valid UTF-8
```

**Comment by MoralCode** [comment]
id be curious if the flatpak has visibility into the current running desktop session. i think this might make it possible to remove the environment variable thats shipping with this flatpak thats causing all these installs to default to basic credential storage

the electron docs talk about detecting the secure storage backend based on desktop session: https://www.electronjs.org/docs/latest/api/safe-storage#safestoragegetselectedstoragebackend-linux

**Comment by bermeitinger-b** [comment]
Yes, it does and should have done correctly. But judging from the backlash and numbers of errors regarding this, it seems that Electron does not behave everywhere equally.

**Comment by AllUsernamesAreFuckinTaken** [comment]
I got that --password-store message too. I was running Xubuntu 24.10 without a problem. Then I installed Kde Plasma and got it.  All I had to do was to edit /usr/share/applications/signal-desktop.desktop and change one line
It looks like the launcher pointed to a previous install in /opt. I wrote a line with the actual path and solved my issue.
But it's curious the warning, because the error was on the path, no database involved. Yeah, a bit late, I know.

[Desktop Entry]
Name=Signal
#Exec=/opt/Signal/signal-desktop  %U
Exec=/usr/bin/signal-desktop - %U
Terminal=false
Type=Application
Icon=signal-desktop
StartupWMClass=Signal
Comment=Private messaging from your desktop
MimeType=x-scheme-handler/sgnl;x-scheme-handler/signalcaptcha;
Categories=Network;InstantMessaging;Chat;

**Comment by kode54** [comment]
Just FYI, it may be pertinent to remove the double quotes from the argument when setting it in a .desktop file, as the spec says the quotes should enclose the entire argument, and they don't look to be necessary for this value anyway.

**Comment by illwieckz** [comment]
This is now 9 months since [after I experienced](https://github.com/flathub/org.signal.Signal/issues/753#issuecomment-2395526086) this bug and it is not fixed yet, so it's now 9 months I had not been able to open Signal on my computer.

**Comment by AllUsernamesAreFuckinTaken** [comment]
> For some reason, despite not having made any major updates on my OS (Fedora Workstation 40), I now get this message when trying to open Signal:
> 
> Database startup error:
> 
> ```
> SafeStorageBackendChangeError: Detected change in safeStorage backend, can't decrypt DB key (previous: gnome_libsecret, current: basic_text)
>     at getSQLKey ([REDACTED]/app/main.js:1256:11)
>     at initializeSQL ([REDACTED]/app/main.js:1317:11)
>     at App.<anonymous> ([REDACTED]/app/main.js:1538:20)
> 
> App Version: 7.24.1
> OS: linux
> ```
> 
> Any idea why this is happening? I've tried opening signal through the terminal with --password-store=gnome-libsecret and --password-store=basic-text. Passing gnome-libsecret as the argument for the command gives me a similar error, but it gives me the option of deleting the database and restarting signal, which I don't want to have to resort to.

I removed Signal along any folders related to, and reinstalled choosing password-store basic text, not gnome or whatever. It works for me.

**Comment by tsegers** [comment]
I didn't manage to launch the Arch Linux version of `signal-desktop` with gnome_libsecret by default through environment variables. What ended up working was placing the text `--password-store=gnome-libsecret` (without quoting the gnome-libsecret value) in `~/.config/signal-desktop-flags.conf`. The script that is `/usr/bin/signal-desktop` will then pass that to the actual signal binary at `/usr/lib/signal-desktop/signal-desktop`. Hope that helps someone having the same issue.

**Comment by bermeitinger-b** [comment]
This does not help at all for the **flatpak** distributed version. I'm closing this.

**Comment by tsegers** [comment]
Apologies. I hadn't checked what repo this issue belonged to at all.
