### ISSUE TITLE
Application won't launch, gives javascript error

### ISSUE THREAD

**Issue by molytov** [flathub/org.signal.Signal#783]
Running the latest version of the application on Fedora 40.
Trying to launch via the terminal and going through the plaintext storage warning, I get the output and error below, and the application doesn't start.
```
Debug: Using password store: basic

Debug: Will run signal with the following arguments: --password-store=basic
Debug: Additionally, user gave: 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT, node_modules/@signalapp/libsignal-client/prebuilds/linux-x64/@signalapp+libsignal-client.node not found in /app/Signal/resources/app.asar
    at createError (node:electron/js2c/node_init:2:2002)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2721)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at c._load (node:electron/js2c/node_init:2:16955)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at load (/app/Signal/resources/app.asar/node_modules/node-gyp-build/node-gyp-build.js:22:10)
    at Object.<anonymous> (/app/Signal/resources/app.asar/node_modules/@signalapp/libsignal-client/Native.js:6:43)
    at Module._compile (node:internal/modules/cjs/loader:1484:14)
^C
$ [2 preload-host-spawn-strategy] Dropping 0x1bf000108d80 (3) because of connection closed
[2:1112/200802.282600:FATAL:bus.cc(1246)] D-Bus connection was disconnected. Aborting.
[2:1112/200802.282945:FATAL:bus.cc(1246)] D-Bus connection was disconnected. Aborting.
```

**Comment by flg** [comment]
Same error. System is AlmaLinux 9.4, up-to-date.

```
$ flatpak info org.signal.Signal

Signal Foundation - Private messenger

          ID: org.signal.Signal
         Ref: app/org.signal.Signal/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 7.34.0
     License: AGPL-3.0-only
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 477.4 MB
     Runtime: org.freedesktop.Platform/x86_64/24.08
         Sdk: org.freedesktop.Sdk/x86_64/24.08

      Commit: bc05d11cf9ed55516a5e46e86a4102c2110d2e24a8c773981463db3b30a731aa
      Parent: 33d8ebbce57248de373981e9eef031c01934b9464b9a386376ea33dbd7aca30c
     Subject: signal-desktop: Update signal-desktop.deb to 7.34.0 (#788) (b9a12c53)
        Date: 2024-11-20 21:44:58 +0000
```

**Comment by diamondburned** [comment]
I'm also getting this error.

<details>
<summary><code>flatpak run</code> output</summary>

```
$ flatpak run org.signal.Signal 
Debug: Using password store: basic
Debug: Will run signal with the following arguments: --password-store=basic
Debug: Additionally, user gave: 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT, node_modules/@signalapp/libsignal-client/prebuilds/linux-x64/@signalapp+libsignal-client.node not found in /app/Signal/resources/app.asar
    at createError (node:electron/js2c/node_init:2:2002)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2721)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at c._load (node:electron/js2c/node_init:2:16955)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at load (/app/Signal/resources/app.asar/node_modules/node-gyp-build/node-gyp-build.js:22:10)
    at Object.<anonymous> (/app/Signal/resources/app.asar/node_modules/@signalapp/libsignal-client/Native.js:6:43)
    at Module._compile (node:internal/modules/cjs/loader:1484:14)
Gtk-Message: 16:11:39.734: Failed to load module "canberra-gtk-module"
Gtk-Message: 16:11:39.734: Failed to load module "pk-gtk-module"
Gtk-Message: 16:11:39.735: Failed to load module "canberra-gtk-module"
Gtk-Message: 16:11:39.735: Failed to load module "pk-gtk-module"
^C
[2:1121/161148.856604:FATAL:bus.cc(1246)] D-Bus connection was disconnected. Aborting.
[2 preload-host-spawn-strategy] Dropping 0x39d800108d80 (3) because of connection closed
```

</details>

<details>
<summary><code>flatpak info</code> output</summary>

```
$ flatpak info org.signal.Signal

Signal Desktop - Private messenger

          ID: org.signal.Signal
         Ref: app/org.signal.Signal/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 7.34.0
     License: AGPL-3.0-only
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 477.4 MB
     Runtime: org.freedesktop.Platform/x86_64/24.08
         Sdk: org.freedesktop.Sdk/x86_64/24.08

      Commit: bc05d11cf9ed55516a5e46e86a4102c2110d2e24a8c773981463db3b30a731aa
      Parent: 33d8ebbce57248de373981e9eef031c01934b9464b9a386376ea33dbd7aca30c
     Subject: signal-desktop: Update signal-desktop.deb to 7.34.0 (#788) (b9a12c53)
        Date: 2024-11-20 21:44:58 +0000
```

</details>

**Comment by diamondburned** [comment]
https://github.com/flathub/org.signal.Signal/issues/751#issuecomment-2460590713 fixes this issue.

**Comment by flg** [comment]
Fix confirmed

**Comment by ghost** [comment]
Issue appears to be resolved for the most part by now. Any new instances of this or a similar problem should be reported in a new issue.
