### ISSUE TITLE
Files with cyrillic characters can't be saved or sent

### ISSUE THREAD

**Issue by Leva8** [flathub/org.signal.Signal#790]
OpenSuse Tumbleweed. KDE-Wayland.
1. Signal dosnt use my theme on save dialog
2. Files with cyrillic characters can't be saved (screenshot).
3. Files with cyrillic characters can't be sent (screenshot2) and after Signal app closed and you relaunch it there is infinite download circle (screenshot3). You cant close this circle - no response to X button. When you send new text message it just disappear.

Here is some cyrillic chars for you to reproduce "кирилиця" .

screenshot
![Screenshot](https://github.com/user-attachments/assets/5bec7c54-065d-4c88-a883-ca0074cbbf15)

screenshot2
![Screenshot2](https://github.com/user-attachments/assets/7b196497-3258-4de1-8c18-aef8efa76a47)

screenshot3
![Screenshot3](https://github.com/user-attachments/assets/8e314fad-6b61-4031-8738-15aec197f5da)

**Comment by genodeftest** [comment]
> 1. Signal dosnt use my theme on save dialog

Signal will use your desktop environment's xdg file portal. This should be the same dialog that any other KDE/Qt application has. Is that true for you? Maybe your desktop environment is misconfigured so it uses Gtk portals instead of KDE portals?

I can't reproduce the issue with sending or saving files. Maybe this issue has been fixed in the meantime?
It has been reported upstream signalapp/Signal-Desktop#5575 but that one has been closed 3 years ago

**Comment by Leva8** [comment]
It still  present.

> 
Render process is gone: Error: Reason: killed, Exit Code: 3
    at App.<anonymous> (/app/Signal/resources/app.asar/app/global_errors.js:94:7)
    at App.emit (node:events:518:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:90152)
    at WebContents.emit (node:events:518:28)
{"level":50,"time":"2025-05-05T07:24:31.629Z","msg":"Render process is gone: Error: Reason: killed, Exit Code: 3\n    at App.<anonymous> ([REDACTED]/app/global_errors.js:94:7)\n    at App.emit (node:events:518:28)\n    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:90152)\n    at WebContents.emit (node:events:518:28)"}
{"level":50,"time":"2025-05-05T07:24:35.086Z","msg":"Error sending from webFrameMain:  {}"}
{"level":50,"time":"2025-05-05T07:24:35.716Z","msg":"Error sending from webFrameMain:  {}"}
{"level":30,"time":"2025-05-05T07:24:59.800Z","msg":"main window closed event"}
{"level":30,"time":"2025-05-05T07:24:59.801Z","msg":"System tray service: updating main window. Previously, there was a window, and now there is not"}
{"level":30,"time":"2025-05-05T07:24:59.801Z","msg":"System tray service: rendering no tray"}
{"level":30,"time":"2025-05-05T07:24:59.801Z","msg":"quit event {\"hasEventBeenPrevented\":false,\"windowCount\":0,\"mainWindowExists\":false}"}
{"level":30,"time":"2025-05-05T07:24:59.805Z","msg":"Updating BrowserWindow config: %s {\"maximized\":true,\"autoHideMenuBar\":true,\"fullscreen\":false,\"width\":1220,\"height\":692,\"x\":0,\"y\":28}"}
{"level":30,"time":"2025-05-05T07:24:59.806Z","msg":"config/set: Saving ephemeral config to disk"}
{"level":30,"time":"2025-05-05T07:24:59.810Z","msg":"config/set: Saved ephemeral config to disk"}

>

**Comment by peteruithoven** [comment]
How can we figure out whether this issue lies with flatpak packaging or Signal?
